name: Testing

on: 
  workflow_dispatch:
  
  pull_request:
    branches:    
      - 'master'
      - 'dev'


jobs:
  Testing:
    uses: 34ML/Actions-Config/.github/workflows/Laravel-Testing.yml@master
    with:
      docker-image: ghcr.io/34ml/docker-laravel:php-7.4-composer-2.0-node-14.15.5
    secrets: inherit # pass all secrets